- name: Install packages and enable services
  ansible.builtin.import_tasks: tasks/install_and_enable.yml
  vars:
    require_service: firewalld

- name: Open the port for http
  ansible.posix.firewalld:
    service: http
    immediate: true
    permanent: true
    state: enabled
