- name: Install packages and enable services 
  ansible.builtin.import_tasks: tasks/install_and_enable.yml 
  vars:
    require_service: httpd 

- name: Tuning configuration installed
  ansible.builtin.copy:
    src: files/tune.conf
    dest: /etc/httpd/conf.d/tune.conf
    owner: root
    group: root
    mode: 0644
  notify:
    - restart httpd

