---
- name: Create a custom fact for controlnode
  hosts: controlnode
  become: true

  tasks:
    - name: Create the /etc/ansible/facts.d 
      ansible.builtin.file:
        path: /etc/ansible/facts.d
        state: directory

    - name: Create the custom.fact in /etc/ansible/facts.d
      ansible.builtin.copy:
        content: "[sample_exam]\nserver_role=mysql"
        dest: /etc/ansible/facts.d/custom.fact
     

