---
- name: Automate the setup of a web server environment on node2
  hosts: webserver
  become: true
  vars:
    firewall_pkg: firewalld
    firewall_svc: firewalld
    web_pkg: httpd
    web_svc: httpd
    ssl_pkg: mod_ssl
    web_root: /var/www/html 

  tasks:    
    - name: Packages are installed
      ansible.builtin.dnf:
        name: 
          - "{{ firewall_pkg }}"
          - "{{ web_pkg }}"
          - "{{ ssl_pkg }}"
        state: latest

    - name: Index.html is created with it content
      ansible.builtin.lineinfile:
        path: "{{ web_root }}/index.html"
        line: "{{ ansible_fqdn }} ({{ ansible_default_ipv4['address'] }}) has been customized by Ansible."
        create: yes
    
    - name: Enable and start the firewall service
      ansible.builtin.systemd:
        state: started
        enabled: true
        name: "{{ firewall_svc }}"

    - name: Allow http service for the users
      ansible.posix.firewalld:
        service: http
        permanent: yes
        state: enabled
        immediate: yes
      
    - name: Enable and start the {{ web_svc }} service
      ansible.builtin.systemd:
        state: started
        enabled: true
        name: "{{ web_svc }}"

- name: Test and verify a return HTTP status code of 200
  hosts: controlnode

  tasks:
    - name: Test the http web
      ansible.builtin.uri:
        status_code: 200
        url: http://node2
        return_content: yes
      register: content_result

    - name: Print the content result
      ansible.builtin.debug:
        msg: "{{ content_result.content }}"    

  
 



