---
- name: Install and configure apache httpd
  hosts: node4
  gather_facts: true
  become: true
  
  tasks:
    - name: Install the required package
      ansible.builtin.dnf:
        name: "{{ ansible_facts.ansible_local.custom.general.package }}"
        state: latest

    - name: Start and enable the service
      ansible.builtin.service:
        name: "{{ ansible_facts['ansible_local']['custom']['general']['service'] }}"
        state: "{{  ansible_facts['ansible_local']['custom']['general']['state'] }}"
        enabled: "{{  ansible_facts['ansible_local']['custom']['general']['enabled'] }}"

    - name: Create index.html file
      ansible.builtin.replace:
        path: /var/www/html/index.html
        regexp: '^(.+)$'
        replace: "{{ ansible_facts['fqdn'] }}: {{ ansible_facts['default_ipv4']['address'] }}: {{ ansible_facts['default_ipv4']['netmask'] }}\n"

