---
- name: Use myvhost role in the playbook
  hosts: node3
  become: true

  pre_tasks:
  - name: pre_tasks message
    ansible.builtin.debug:
      msg: 'Ensure web server is configured.'

  roles:
    - myvhost

  post_tasks:
  - name: post_tasks message
    ansible.builtin.debug:
      msg: 'Web server is configured.'
