---
- name: Deploy and start Apache HTTPD service
  hosts: node4
  become: true
  vars:
    web_pkg: httpd
    firewall_pkg: firewalld
    web_service: httpd
    firewall_service: firewalld
    python_pkg: python3-PyMySQL
    rule: http

  tasks:    
    - name: Required packages are installed and up to date
      ansible.builtin.dnf:
        name: 
          - "{{ web_pkg }}"
          - "{{ firewall_pkg }}"
          - "{{ python_pkg }}"
        state: latest

    - name: The {{ firewall_service }} service is started and enabled
      ansible.builtin.service:
        name: "{{ firewall_service }}"
        state: started
        enabled: true
      
    - name: The {{ web_service }} service is started and enabled
      ansible.builtin.service:
        name: "{{ web_service }}"
        state: started
        enabled: true

    - name: Web content is in place 
      ansible.builtin.copy:
        content: "Example web content"
        dest: /var/www/html/index.html

    - name: The firewall port for {{ rule }} is open
      ansible.posix.firewalld:
        service: "{{ rule }}"
        permanent: yes
        immediate: yes
        state: enabled

- name: Verify the Apache service
  hosts: controlnode
  tasks:
    - name: Ensure the webserver is reachable
      ansible.builtin.uri:
        url: http://node4

  
