---
- name: Generate the /etc/myhosts file
  hosts: all
  become: true

  tasks:
    - name: Use the hosts.j2 to generate /etc/myhosts file
      ansible.builtin.template:
        src: hosts.j2
        dest: /etc/myhosts
      delegate_to: "{{ item }}"
      loop: "{{ groups['test'] }}"

    #when: "'test' in group_names" 
