---
- name: Generate a hardware report
  hosts: all
  become: true

  tasks:
    - name: Generate /root/hwreport.txt from hwreport.empty 
      ansible.builtin.template:
        src: hwreport.empty
        dest: /root/hwreport.txt
