---
- name: Configure the LVM
  hosts: all
  become: true

  tasks:
   
    - name: Display a fail message when research does not exist
      ansible.builtin.debug:
        msg: "research vg does not exist"
      when: ansible_lvm.vgs.research is not defined

    - name: Create the logical volume
      block:
        - name: Create lv if research exist and has enough space
          community.general.lvol:
            vg: research
            lv: mylv
            size: 1500
      rescue:
        - name: Display a fail message when the space is not enough
          ansible.builtin.debug:
            msg: "Could not create logical volume of that size"

        - name: Create lv of 800MiB instead
          community.general.lvol:
            vg: research
            lv: mylv
            size: 800

    - name: Format the filesystem
      community.general.filesystem:
        dev: /dev/research/mylv
        fstype: ext4
     
    - name: Mount the file system
      ansible.posix.mount:
        path: /data
        src: /dev/research/mylv
        fstype: ext4
        state: mounted
      when: inventory_hostname in groups['proxy']    

                  
      


