---
- name: Manage automation user and SSH 
  hosts: all
  remote_user: root

  tasks:
    - name: Create the automation user and set the password
      ansible.builtin.user: 
        name: automation
        state: present
        shell: /bin/bash
        password: "{{ 'devops' | password_hash('sha512') }}"
        update_password: on_create

    - name: Configure the authorized_key
      ansible.posix.authorized_key:
        user: automation
        state: present
        key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"

    - name: Configure the sudo access for automation user
      ansible.builtin.lineinfile:
        path: /etc/sudoers
        state: present
        line: 'automation ALL=(ALL) NOPASSWD: ALL'
        validate: /usr/sbin/visudo -cf %s
      
   
