---
- name: Scheduled a task
  hosts: proxy
  become: true

  tasks:
    - name: Create a cron job
      ansible.builtin.cron:
        name: Add date and time
        weekday: "1-5"
        minute: "*/2"
        hour: "9-23"
        user: automation
        job: "/usr/bin/date >> /tmp/time.log"
        cron_file: add-date-time

