---
- name: Configure yum repository
  hosts: all
  become: yes
  tasks:

    - name: Create a custom yum repository file
      ansible.builtin.yum_repository:
        name: Exam_RHEL
        description: EX294 software
        baseurl: https://dl.fedoraproject.org/pub/epel/epel-release-latest-9.noarch.rpm
        gpgcheck: yes
        enabled: no

    - name: Import a key from a url
      ansible.builtin.rpm_key:
        state: present
        key: https://dl.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-9

    - name: yum-clean-metadata
      ansible.builtin.command: yum clean metadata
      changed_when: false
      
     
