---
- name: Configure selinux boolean
  hosts: webservers
  become: true
  vars:
    selinux_booleans:
      - name: httpd_can_network_connect 
        state: true
        persistent: true

  roles:        
    - selinux

